-- Stories table seeds here (Example)
INSERT INTO stories (user_id, content, title, time_created, time_completed) VALUES (1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'A short story', CURRENT_TIMESTAMP, NULL);

INSERT INTO stories (user_id, content, title, time_created, time_completed) VALUES (2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id semper risus in hendrerit gravida rutrum quisque. Quis imperdiet massa tincidunt nunc pulvinar. Mus mauris vitae ultricies leo integer malesuada nunc vel. Posuere urna nec tincidunt praesent semper feugiat nibh. Commodo viverra maecenas accumsan lacus vel. Dignissim diam quis enim lobortis scelerisque fermentum. Convallis convallis tellus id interdum velit laoreet id donec. Nullam ac tortor vitae purus faucibus. Convallis tellus id interdum velit laoreet id. Donec adipiscing tristique risus nec feugiat in. Proin libero nunc consequat interdum varius sit amet mattis.', 'Another short story', CURRENT_TIMESTAMP, NULL);

INSERT INTO stories (user_id, content, title, time_created, time_completed) VALUES (3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium. Nibh mauris cursus mattis molestie. Tortor dignissim convallis aenean et tortor at. Feugiat nibh sed pulvinar proin. In mollis nunc sed id semper risus in hendrerit gravida. Adipiscing tristique risus nec feugiat. Nam at lectus urna duis convallis convallis. Vel eros donec ac odio tempor orci dapibus ultrices. Morbi non arcu risus quis varius quam quisque id. Tempus urna et pharetra pharetra. Magnis dis parturient montes nascetur ridiculus mus mauris. Lacus sed turpis tincidunt id aliquet risus feugiat in. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Eget mauris pharetra et ultrices neque ornare aenean. Praesent tristique magna sit amet. Mauris a diam maecenas sed. Maecenas sed enim ut sem viverra aliquet. Sed blandit libero volutpat sed cras ornare arcu. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus.', 'Again a short story', CURRENT_TIMESTAMP, NULL);

INSERT INTO stories (user_id, content, title, time_created, time_completed) VALUES (4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Consectetur a erat nam at lectus urna duis convallis convallis. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Pharetra vel turpis nunc eget lorem dolor sed. Urna porttitor rhoncus dolor purus non. Netus et malesuada fames ac turpis egestas. Morbi tristique senectus et netus et. Maecenas sed enim ut sem viverra aliquet eget sit. Morbi tristique senectus et netus et malesuada. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. In fermentum et sollicitudin ac orci phasellus egestas tellus. Quis commodo odio aenean sed adipiscing diam donec adipiscing tristique.', 'A really good short story', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO stories (user_id, content, title, time_created, time_completed) VALUES (5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sed viverra tellus in hac habitasse. Iaculis urna id volutpat lacus laoreet. Adipiscing enim eu turpis egestas pretium aenean pharetra. Bibendum est ultricies integer quis auctor. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Consectetur libero id faucibus nisl tincidunt eget nullam. Augue eget arcu dictum varius duis at consectetur. Vel facilisis volutpat est velit egestas dui id ornare arcu. Etiam erat velit scelerisque in dictum. Amet venenatis urna cursus eget nunc scelerisque. Vulputate mi sit amet mauris commodo quis imperdiet. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus.', 'A clever title', CURRENT_TIMESTAMP, NULL);






